/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.tables.references


import org.jooq.mcve.kotlin.tables.Test



/**
 * The table <code>MCVE.TEST</code>.
 */
val TEST = Test.TEST
