name: Feature Request
description: Suggest an idea
labels: ["T: Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        <strong>This is for reporting bugs about the MCVE template! Please report issues about jOOQ here, instead: https://github.com/jOOQ/jOOQ/issues/new/choose</strong>

        Please describe the use-case you have. This will better help us understand the context in which you're looking for a new feature.
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: |
        Please describe the use-case you have. This will better help us understand the context in which you're looking for a new feature.
      placeholder: Describe the use-case here
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible solution
      description: |
        Please describe a possible solution you'd like to see in the jOOQ-mcve template, ideally with example code.
        Please note, it's not always easy to describe a good solution. Describing the use-case above is much more important to us.
      placeholder: Describe the possible solution here.
    validations:
      required: false
  - type: textarea
    id: workarounds
    attributes:
      label: Possible workarounds
      description: |
        Please describe the possible workarounds you've implemented to work around the lacking functionality.
      placeholder: Describe the possible workarounds here.
    validations:
      required: false
