/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import org.jooq.mcve.scala.tables.Test


/**
 * Convenience access to all tables in MCVE.
 */
object Tables {

  /**
   * The table <code>MCVE.TEST</code>.
   */
  def TEST = Test.TEST
}
