/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.mcve.java.tables.Test;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mcve extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MCVE</code>
     */
    public static final Mcve MCVE = new Mcve();

    /**
     * The table <code>MCVE.TEST</code>.
     */
    public final Test TEST = Test.TEST;

    /**
     * No further instances allowed
     */
    private Mcve() {
        super("MCVE", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Test.TEST);
    }
}
